### PR TITLE
Fixes for v2018.09.04

### PR DESCRIPTION
**Pull request by andswitch**
1. Fix type of `ycmd_completions`
2. Add `evaluate-commands` where necessary
3. Add default `.ycm_extra_conf.py` to options to stop ycmd from complaining.
4. Change `python` to `python3`
5. Added fixes from https://github.com/danr/kak-ycmd/commit/63476dc85741c99f05ba613f277aab7afdb1625a
6. Use `printf` instead of `echo` for hmac calculation. `echo` breaks the output from `jq` due to interpretation of escape sequences.
7. Change the way `ycmd_completions` is added to/removed from the completer list so that it works with v2018.09.04.

### CODE REVIEW

**Comment by mawww** [comment]
Wow, thanks for that, I did not know kak-ycmd was still used in  the wild.

**Comment by andswitch** [comment]
> Wow, thanks for that, I did not know kak-ycmd was still used in the wild.

You're welcome! Kakoune is a cool project. I actually don't know how useful ycmd support is. I was just playing around with it. So when I realized it's not working I thought I can try to fix it and might as well submit a patch.

**Comment by mawww** [comment]
Could you cleanup that history a bit ? squash the readme updates together, squash logically related commits together as well.

**Comment by andswitch** [comment]
> Could you cleanup that history a bit ? squash the readme updates together, squash logically related commits together as well.

I'm actually still messing around with it a lot. I will close the pull request for now and prepare a better one when I'm happy with the result.

**Pull request closed without merging**
